language: ruby
cache: bundler

script: ./update

before_script:
 - chmod +x ./update

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
